---
- name: Manage 0gchaind service and clean up data
  hosts: '{{ target }}'
  become: yes
  tasks:
    - name: Stop 0gchaind service
      systemd:
        name: 0gchaind
        state: stopped

    - name: Remove tx_index.db directory
      command: sudo rm -r "{{ ansible_env.HOME }}/.story/story/data/tx_index.db"
      args:
        removes: "{{ ansible_env.HOME }}/.story/story/data/tx_index.db"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart 0gchaind service
      systemd:
        name: 0gchaind
        state: restarted
